version: '2'
services:
  fastlogger:
    image: vilsol/fastlogger
    restart: always
    ports:
     - 8080:8080
    volumes:
     - ./speed-log.txt:/speed-log.txt
    environment:
     - TZ=Europe/Riga
